### ISSUE TITLE
翻译&校对贡献者列表

### ISSUE THREAD

**Issue by 70data** [volksbright/document-standard-vue#192]
这里汇聚了所有参与翻译&校对的人员名单（包括提过pull request被merge）。

此页面会持续更新。

### Essentials  基础
| 序号 | 对应文档文件名 | 中文标题 | 翻译贡献者 | 校对主要贡献者 |
| --- | --- | --- | --- | --- |
| 1 | installation.md | 安装 | [dingyiming](https://github.com/dingyiming) | [ATLgo](https://github.com/ATLgo) [70data](https://github.com/70data) |
| 2 | index.md | 介绍 | [hijiangtao](https://github.com/hijiangtao) | [70data](https://github.com/70data) [ATLgo](https://github.com/ATLgo) |
| 3 | instance.md | 实例 | [dingyiming](https://github.com/dingyiming) | [70data](https://github.com/70data) [ATLgo](https://github.com/ATLgo) |
| 4 | syntax.md | 模板语法 | [daix6](https://github.com/daix6) | [70data](https://github.com/70data) |
| 5 | computed.md | 计算属 性 | [dingyiming](https://github.com/dingyiming) [70data](https://github.com/70data) | [70data](https://github.com/70data) |
| 6 | class-and-style.md | Class 与 Style 绑定 | [595074187](https://github.com/595074187) | [70data](https://github.com/70data) |
| 7 | conditional.md | 条件渲染 | [dingyiming](https://github.com/dingyiming) | [hgcoder](https://github.com/hgcoder) |
| 8 | list.md | 列表渲染 | [tingtien](https://github.com/tingtien) | [hgcoder](https://github.com/hgcoder) |
| 9 | events.md | 事件处理器 | [dingyiming](https://github.com/dingyiming) | [yangzj1992](https://github.com/yangzj1992) |
| 10 | forms.md | 表单控件绑定 | [dingyiming](https://github.com/dingyiming) | [yangzj1992](https://github.com/yangzj1992) |
| 11 | components.md | 组件 | [ezreally](https://github.com/ezreally) | [cuiyongjian](https://github.com/cuiyongjian) |

### Advanced  进阶
| 序号 | 对应文档文件名 | 中文标题 | 翻译贡献者 | 校对主要贡献者 |
| --- | --- | --- | --- | --- |
| 12 | transitions.md | 过渡: 进入, 离开, 和 列表 | [awe](https://github.com/awe) | [bhnddowinf](https://github.com/bhnddowinf) [StoneQI](https://github.com/StoneQI) |
| 13 | transitioning-state.md | 过渡状态 | [awe](https://github.com/awe) | [bhnddowinf](https://github.com/bhnddowinf) |
| 14 | render-function.md | Render 函数 | [awe](https://github.com/awe) | [bhnddowinf](https://github.com/bhnddowinf) |
| 15 | reactivity.md | 深入响应式原理 | [veaba](https://github.com/veaba) | [yangzj1992](https://github.com/yangzj1992) |
| 16 | custom-directive.md | 自定义指令 | [70data](https://github.com/70data) | [yangzj1992](https://github.com/yangzj1992) |
| 17 | mixins.md | 混合 | [70data](https://github.com/70data) | [bhnddowinf](https://github.com/bhnddowinf) |
| 18 | plugins.md | 插件 | [hgcoder](https://github.com/hgcoder) | [hgcoder](https://github.com/hgcoder) |
| 19 | single-file-components.md | 单文件组件 | [ATLgo](https://github.com/ATLgo) | [zhouzihanntu](https://github.com/zhouzihanntu) |
| 20 | routing.md | 路由 | [dingyiming](https://github.com/dingyiming) | [mlyknown](https://github.com/mlyknown) |
| 21 | state-management.md | 状态管理 | [dear-lizhihua](https://github.com/dear-lizhihua) | [mlyknown](https://github.com/mlyknown) |
| 22 | unit-testing.md | 单元测试 | [70data](https://github.com/70data) | [mlyknown](https://github.com/mlyknown) |
| 23 | ssr.md | 服务端渲染 | [dingyiming](https://github.com/dingyiming) | [yongbolv](https://github.com/yongbolv) |

### Migration  迁移
| 序号 | 对应文档文件名 | 中文标题 | 翻译贡献者 | 校对主要贡献者 |
| --- | --- | --- | --- | --- |
| 24 | migration.md | 1.x迁移 | [70data](https://github.com/70data) | [yongbolv](https://github.com/yongbolv) |
| 27 | migration-vue-router.md | vue-router 0.7.x 迁移 | [forzajuve10](https://github.com/forzajuve10) | [yizhixiaolongxia](https://github.com/yizhixiaolongxia) |

### Meta  更多
| 序号 | 对应文档文件名 | 中文标题 | 翻译贡献者 | 校对主要贡献者 |
| --- | --- | --- | --- | --- |
| 25 | comparison.md | 对比其他框架 | [yongbolv](https://github.com/yongbolv) | [yangzj1992](https://github.com/yangzj1992) |
| 26 | join.md | 加入 Vue.js 社区 | [daix6](https://github.com/daix6) | [zhouzihanntu](https://github.com/zhouzihanntu) |

## API 部分
| 序号 | 对应小节名称 | 中文标题 | 翻译贡献者 | 校对主要贡献者 |
| --- | --- | --- | --- | --- |
| 1 | Global Config | 全局配置 | [dear-lizhihua](https://github.com/dear-lizhihua) | [bhnddowinf](https://github.com/bhnddowinf) |
| 2 | Global API | 全局 API | [dear-lizhihua](https://github.com/dear-lizhihua) | [bhnddowinf](https://github.com/bhnddowinf) |
| 3 | Options / Data | 选项 / 数据 | [dear-lizhihua](https://github.com/dear-lizhihua) | [bhnddowinf](https://github.com/bhnddowinf) |
| 4 | Options / DOM | 选项 / DOM | [ATLgo](https://github.com/ATLgo) | [bhnddowinf](https://github.com/bhnddowinf) |
| 5 | Options / Lifecycle Hooks | 选项 / 生命周期钩子 | [ATLgo](https://github.com/ATLgo) | [bhnddowinf](https://github.com/bhnddowinf) |
| 6 | Options / Assets | 选项 / 资源 | [dingyiming](https://github.com/dingyiming) | [bhnddowinf](https://github.com/bhnddowinf) |
| 7 | Options / Misc | 选项 / 杂项 | [dingyiming](https://github.com/dingyiming) | [bhnddowinf](https://github.com/bhnddowinf) |
| 8 | Instance Properties | 实例属性 | [coolzjy](https://github.com/coolzjy) | [bhnddowinf](https://github.com/bhnddowinf) |
| 9 | Instance Methods / Data | 实例方法 / 数据 | [dingyiming](https://github.com/dingyiming) | [bhnddowinf](https://github.com/bhnddowinf) |
| 10 | Instance Methods / Events | 实例方法 / 事件 | [mlyknown](https://github.com/mlyknown) | [bhnddowinf](https://github.com/bhnddowinf) |
| 11 | Instance Methods / Lifecycle | 实例方法 / 生命周期 | [mlyknown](https://github.com/mlyknown) | [bhnddowinf](https://github.com/bhnddowinf) |
| 12 | Directives | 指令 | [dingyiming](https://github.com/dingyiming) | [bhnddowinf](https://github.com/bhnddowinf) |
| 13 | Special Attributes | 特殊元素 | [70data](https://github.com/70data) | [bhnddowinf](https://github.com/bhnddowinf) |
| 14 | Built-In Components | 内置的组件 | [dear-lizhihua](https://github.com/dear-lizhihua) | [bhnddowinf](https://github.com/bhnddowinf) |
| 15 | VNode Interface | VNode 接口 | [70data](https://github.com/70data) | [dear-lizhihua](https://github.com/dear-lizhihua) |
| 16 | Server-Side Rendering | 服务端渲染 | [70data](https://github.com/70data) | [dear-lizhihua](https://github.com/dear-lizhihua) |

## example 部分
贡献者  [lindazhang102](https://github.com/lindazhang102)

## vuex部分
| 序号 | 文件名 | 中文标题 | 翻译贡献者 |
| --- | --- | --- | --- |
| 1 | installation.md | 安装 | [ATLgo](https://github.com/ATLgo) |
| 2 | intro.md | 什么是 Vuex ？ | [ATLgo](https://github.com/ATLgo) |
| 3 | getting-started.md | 起步 | [ATLgo](https://github.com/ATLgo) |
| 4 | state.md | State | [dear-lizhihua](https://github.com/dear-lizhihua) |
| 5 | getters.md | Getters | [dear-lizhihua](https://github.com/dear-lizhihua) |
| 6 | mutations.md | Mutations | [dear-lizhihua](https://github.com/dear-lizhihua) |
| 7 | actions.md | Actions | [dear-lizhihua](https://github.com/dear-lizhihua) |
| 8 | modules.md | Modules | [yongbolv](https://github.com/yongbolv) |
| 9 | structure.md | 应用结构 | [yongbolv](https://github.com/yongbolv) |
| 10 | plugins.md | 插件 | [yongbolv](https://github.com/yongbolv) |
| 11 | strict.md | 严格模式 | [yongbolv](https://github.com/yongbolv) |
| 12 | forms.md | 表单处理 | [veaba](https://github.com/veaba) |
| 13 | testing.md | 测试 | [veaba](https://github.com/veaba) |
| 14 | hot-reload.md | 热加载 | [mlyknown](https://github.com/mlyknown) |
| 15 | api.md | API | [mlyknown](https://github.com/mlyknown) |

## 所有参与校对人员名单：
| Github Name | Github Name | Github Name | Github Name | Github Name |
| --- | --- | --- | --- | --- |
| [tuxiantian](https://github.com/tuxiantian) | [showonne](https://github.com/showonne) | [Luoxinfang](https://github.com/Luoxinfang) | [xie-qianyue](https://github.com/xie-qianyue) | [rocklau](https://github.com/rocklau) |
| [shoglory](https://github.com/shoglory) | [viko16](https://github.com/viko16) | [Creabine](https://github.com/Creabine) | [panzj](https://github.com/panzj) | [shupande](https://github.com/shupande) |
| [ShangXinbo](https://github.com/ShangXinbo) | [swust-xiaoj](https://github.com/swust-xiaoj) | [lichunqiang](https://github.com/lichunqiang) | [Orange-C](https://github.com/Orange-C) | [athena0304](https://github.com/athena0304) |
| [tttpeng](https://github.com/tttpeng) | [zhouxinyong](https://github.com/zhouxinyong) | [LightCi](https://github.com/LightCi) | [MrZhang123](https://github.com/MrZhang123) | [XyinM](https://github.com/XyinM) |
| [homfen](https://github.com/homfen) | [sleelily](https://github.com/sleelily) | [varHarrie](https://github.com/varHarrie) | [fytriht](https://github.com/fytriht) | [yuzhiquan](https://github.com/yuzhiquan) |
| [LeoSpark](https://github.com/LeoSpark) | [liyahui](https://github.com/liyahui) | [477800969](https://github.com/477800969) | [skiy](https://github.com/skiy) | [green-mike](https://github.com/green-mike) |
| [G-Bruin](https://github.com/G-Bruin) | [geekingin](https://github.com/geekingin) | [amingguazi](https://github.com/amingguazi) | [NangeGao](https://github.com/NangeGao) | [Gavin-Gong](https://github.com/Gavin-Gong) |
| [bringtree](https://github.com/bringtree) | [lihengming](https://github.com/lihengming) | [iHelin](https://github.com/iHelin) | [kiyonlin](https://github.com/kiyonlin) | [xqin](https://github.com/xqin) |
| [zp1996](https://github.com/zp1996) | [ZHKO1](https://github.com/ZHKO1) | [crowphy](https://github.com/crowphy) | [Peter-WF](https://github.com/Peter-WF) | [ZoeyYoung](https://github.com/ZoeyYoung) |
| [think2011](https://github.com/think2011) | [xalexec](https://github.com/xalexec) | [yanlee26](https://github.com/yanlee26) | [psaren](https://github.com/psaren) | [keyfoxth](https://github.com/keyfoxth) |
| [MrXin](https://github.com/MrXin) | [NameLi](https://github.com/NameLi) | [zvit1](https://github.com/zvit1) | [B1anker](https://github.com/B1anker) | [shellphon](https://github.com/shellphon) |
| [Andself](https://github.com/Andself) | [zhyihui](https://github.com/zhyihui) | [lerte](https://github.com/lerte) | [STayinloves](https://github.com/STayinloves) | [muyunz](https://github.com/muyunz) |
| [lhcpig](https://github.com/lhcpig) | [JeremyFan](https://github.com/JeremyFan) | [daniel48](https://github.com/daniel48) | [tuj1n](https://github.com/tuj1n) | [raxxarr](https://github.com/raxxarr) |
| [popomore](https://github.com/popomore) | [tangciwei](https://github.com/tangciwei) | [DreamColl](https://github.com/DreamColl) | [HollyHigh](https://github.com/HollyHigh) | [yhtml5](https://github.com/yhtml5) |
| [chaoren1641](https://github.com/chaoren1641) | [soyal](https://github.com/soyal) | [solicomo](https://github.com/solicomo) | [kidlj](https://github.com/kidlj) | [MeCKodo](https://github.com/MeCKodo) |
| [tolerious](https://github.com/tolerious) | [galenyuan](https://github.com/galenyuan) | [zuzhi](https://github.com/zuzhi) | [Remember2015](https://github.com/Remember2015) |  [Lesty612](https://github.com/Lesty612) |
| [yinzuojie](https://github.com/yinzuojie) | [DevinZhong](https://github.com/DevinZhong) | [plain1994](https://github.com/plain1994) | [1987539447](https://github.com/1987539447) | [foolyoghurt](https://github.com/foolyoghurt) |
| [airt](https://github.com/airt) | [tangxiaolang101](https://github.com/tangxiaolang101) | [liadbiz](https://github.com/liadbiz) | [LionNatsu](https://github.com/LionNatsu) | [magicknight](https://github.com/magicknight) |
| [uiblog](https://github.com/uiblog) | [YXDay](https://github.com/YXDay) | [DanielWLam](https://github.com/DanielWLam) | [shaoxiong789](https://github.com/shaoxiong789) | [wipphj](https://github.com/wipphj) |
| [DaErDuo](https://github.com/DaErDuo) |  |  |  |  |

再次感谢所有为 Vue2.0 翻译做出贡献的人。

如有遗漏或者问题请及时回复。

**Comment by dingyiming** [comment]
@70data 需要把 @ 名字 改成 链接式的，这样可以粘贴到多处

**Comment by 70data** [comment]
已修改

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/19503525/bd043f9a-95e6-11e6-8477-57c6c63682d1.png)

**Comment by gongph** [comment]
你好，我也参与了翻译。请知晓！

**Comment by 70data** [comment]
@gongph  请问你的pr是？

**Comment by liud5120** [comment]
# 阿斯顿发送地方

**Comment by DaErDuo** [comment]
Vue 教程的 [列表渲染](https://cn.vuejs.org/v2/guide/list.html#v-for-with-v-if) 中有处错误：
`v-for` 的优先级比 `v-if` 更高，这意味着 `v-if` 将分别重复运行于每个 `v-if` 循环中。

最后一个 `v-if` 应该是 `v-for` 吧

**Comment by yalishizhude** [comment]
已提交PR，求进入名单~
谢谢~
https://github.com/vuejs/cn.vuejs.org/pull/320

**Comment by dear-lizhihua** [comment]
@yalishizhude 除了这一个单词，还有其他贡献吗？

**Comment by kklam2** [comment]
基础-列表渲染-组件 和 v-for-todolist例子-Html部分
  <li
      is="todo-item"
      v-for="(todo, index) in todos"
      v-bind:title="todo"
      v-on:remove="todos.splice(index, 1)"
    ></li>
请及时修改，感谢

**Comment by dear-lizhihua** [comment]
@kklam2 近期我会抽时间校对。

**Comment by dear-lizhihua** [comment]
@kklam2 v-for-todolist 的链接有吗？找不到你说的

**Comment by whysqwhw** [comment]
有没有vue的GEF的demo？

**Comment by dear-lizhihua** [comment]
@whysqwhw 什么是 GEF？
